server:
  port: 8510
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maintenance_support?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  swagger:
    enabled: true
